config/routes.rb
Rails.application.routes.draw do

  root 'meals#index'
  patch 'ingredients/:id/update_list' => 'ingredients#add_or_remove_list', as: :update_list
  resources :meals do
    resources :ingredients
      collection do
        get 'shopping_list', as: :list
      end
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :meal

  FOODGROUPS = ["Grains", "Protein", "Vegetables", "Fruits", "Dairy"]
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :ingredients

  DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
  MEALS = ["Breakfast", "Lunch", "Dinner"]

  def food_groups
    food_group_array = self.ingredients.map do |i|
      i.food_group
    end
    food_group_array.uniq!
    food_group_array.reject! {|i| i == ""}
    return food_group_array
  end

  def needed_food_groups
    needed_groups = ["Grains", "Protein", "Vegetables", "Fruits", "Dairy"]
    have_groups = self.food_groups
    have_groups.map do |group|
      needed_groups.reject! {|g| g == group }
    end
    return needed_groups
  end


  def needed(group)
    have = self.food_groups.include?(group)
    return have ? "selected" : "needed"
  end

  def food_group_count
    self.food_groups.length
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @meal = Meal.find(params[:meal_id])
    @ingredients = @meal.ingredients
    @ingredient = Ingredient.new
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    Ingredient.create(ingredient_params[:ingredient])
    redirect_to meal_ingredients_path(params[:meal_id])
  end

  def destroy
    Ingredient.destroy(params[:id])
    redirect_to meal_path(params[:meal_id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    Ingredient.update(params[:id], ingredient_params[:ingredient])
    redirect_to meal_path(params[:meal_id])
  end

  def add_or_remove_list
    i = Ingredient.find(params[:id])
    if i.shopping_list == true
      Ingredient.update(i.id, shopping_list: false)
    else
      Ingredient.update(i.id, shopping_list: true)
    end
    redirect_to list_meals_path
  end

  private

  def ingredient_params
    params.permit(ingredient:[:ingredient_name, :food_group, :shopping_list, :meal_id])

  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.all
  end

  def new
    @meal = Meal.new
  end

  def create
    new_meal = Meal.create(meal_params[:meal])
    redirect_to meal_ingredients_path(new_meal)
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    Meal.update(params[:id], meal_params[:meal])
    redirect_to meal_path(params[:id])
  end

  def destroy
    Meal.destroy(params[:id])
    redirect_to root_path
  end

  def shopping_list
    @ingredients = Ingredient.all
  end

  private

  def meal_params
    params.permit(meal:[:meal, :day, :meal_name, :description, :food_groups])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/ingredients/_ingredientform.html.erb
<fieldset>
  <%= form_for ingredient, url:{ action: action} do |f| %>
  <legend> <h1><%= title %> </h1></legend>
    <%= f.label :ingredient_name %>
    <%= f.text_field :ingredient_name %><br>
    <%= f.label :food_group %>
    <%= f.select(:food_group, Ingredient::FOODGROUPS, {include_blank: true}) %><br>
    <%= f.label :shopping_list, :value => "Add to Shopping List" %>
    <%= f.check_box :shopping_list %><br>
    <%= f.hidden_field :meal_id, value: meal_id %>
    <%= f.submit %>

  <% end %>

</fieldset>

app/views/ingredients/edit.html.erb
<div class="page_detail">
  <%= render partial: 'ingredientform',
  locals:{ ingredient: @ingredient, action: :update, meal_id: params[:meal_id], title: "Edit Ingredient"}%>
</div>

app/views/ingredients/index.html.erb
<div class="page_detail">
  <h1><%= @meal.day %> <%= @meal.meal %></h1>

    <h2> <%= @meal.meal_name %><br> </h2>
      <p>
        <%= @meal.description %>
      </p>

      <% groups = @meal.food_group_count %>

      <% if groups == 0 %>
        <p>You don't have any food groups yet. Add ingredients below to make a complete meal.</p>
      <% elsif groups == 1 %>
        <p>Your meal has only one food group. Add more ingredients below to make a complete meal.</p>
      <% elsif groups == 2 %>
        <p>Your meal has only two food groups. Add more ingredients below to make a complete meal.</p>
      <% elsif groups == 3 || groups == 4 %>
        <p>Nice job! Your meal has <%= groups %> food groups.</p>
      <% elsif groups == 5 %>
        <p>Wow! You have all five food groups in this meal.  </p>
      <% end %>

      <% if groups < 5 %>
        <p>
          Try adding <%= @meal.needed_food_groups.to_sentence(:last_word_connector => ' or ') %> to make a more complete meal.
        </p>
      <% end %>




    <div class="plate">
      <%= image_tag("fruits.jpg", :class => "top_left " + @meal.needed("Fruits") )%>
      <%= image_tag("grains.jpg", :class => "top_right " + @meal.needed("Grains")) %>
      <%= image_tag("dairy.jpg", :class => "outside_top " + @meal.needed("Dairy"))  %>
      <%= image_tag("vegetables.jpg", :class => "bottom_left " + @meal.needed("Vegetables")) %>
      <%= image_tag("protein.jpg", :class => "bottom_right " + @meal.needed("Protein")) %>
    </div>



  </p>

  <%= link_to '<i class="fa fa-pencil-square-o"></i> Edit Meal'.html_safe, edit_meal_path(params[:meal_id]), class: :button %>
  <%= link_to '<i class="fa fa-trash-o"></i> Delete Meal'.html_safe, meal_path(params[:meal_id]), method: :delete, class: :button, data: { confirm: "Are you sure?" } %>

  <h3>Ingredients</h3>

  <ul>
    <% @ingredients.each do |i| %>
    <li>
      <%= i.ingredient_name.capitalize + " - " + i.food_group %>
      <%= link_to '<i class="fa fa-pencil-square-o pencil_icon"></i>'.html_safe, edit_meal_ingredient_path(params[:meal_id], i.id) %>
      <%= link_to '<i class="fa fa-trash-o trash_icon"></i>'.html_safe, meal_ingredient_path(params[:meal_id], i.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
    <% end %>

  </ul>

  <%= render partial: 'ingredientform',
  locals:{ ingredient: @ingredient, action: :create, meal_id: params[:meal_id], title: "Add an Ingredient"}%>
  </div>


</div>

app/views/ingredients/new.html.erb
<div class="page_detail">
<%= render partial: 'ingredientform',
locals:{ ingredient: @ingredient, action: :create, meal_id: params[:meal_id], title: "Add an Ingredient"}%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPlate Meal Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to "Meal Plan", meals_path %>
    <%= link_to "Shopping List", list_meals_path %>
  </nav>

<%= yield %>

</body>
</html>

app/views/meals/_mealform.html.erb
<fieldset>
  <%= form_for meal, url:{action: action } do |f| %>
  <legend><h1><%= title + " for #{day} #{meal_type}"%></h1>  </legend>
    <!-- <%= f.label :day %>
    <%= f.select(:day, Meal::DAYS, {include_blank: false}) %>
    <%= f.label :meal %>
    <%= f.select(:meal, Meal::MEALS, {include_blank: false}) %> -->
    <%= f.label :meal_name %><br>
    <%= f.text_field :meal_name %> <br><br>
    <%= f.label :description %><br>
    <%= f.text_area :description %><br><br>
    <%= f.hidden_field :day, :value => "#{day}" %>
    <%= f.hidden_field :meal, :value => "#{meal_type}" %>
    <%= f.submit %>

  <% end %>

</fieldset>

app/views/meals/edit.html.erb
<div class="page_detail">
  <%= render partial:'mealform',
            locals:{meal: @meal, action: :update, title: "Edit Meal", day: @meal.day, meal_type: @meal.meal} %>
</div>

app/views/meals/index.html.erb
<h1>Welcome to MyPlate Meal Planner</h1>

<div class="center">
  <%= image_tag("myplate.jpg") %>
</div>


<table>
  <thead>
    <tr>
      <td></td>
      <% Meal::DAYS.each do |day| %>
      <th>
        <%= day %>
      </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
      <% Meal::MEALS.each do |meal| %>
      <tr>
      <th>
        <%= meal %>
      </th>
        <% Meal::DAYS.each do |day| %>
          <% day_meal = Meal.where("meal = ? AND day = ?", meal, day ) %>
        </div>
        <td>
          <% if day_meal == [] %>
            <% table_class = "add_" + meal.downcase %>
            <div class="week <%= table_class %>">
              <%= link_to "Add #{meal}", "/meals/new/?day=#{day}&meal_type=#{meal}" %>
            </div>
          <% else %>
            <% day_meal.each do |m| %>
            <div class="week <%= m.meal.downcase %>">
              <%= link_to m.meal_name , meal_ingredients_path(m) %>
            </div>
            <% end %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/meals/new.html.erb
<div class="page_detail">
  <%= render partial:'mealform',
      locals:{meal: @meal, action: :create, title: "Add a Meal", day: params[:day], meal_type: params[:meal_type]} %>
  <%= render partial:'/ingredients/ingredientform',
      locals:{ :ingredient => Ingredient.new, action: :create, meal_id: params[:meal_id], title: "Add an Ingredient"}%>
</div>

app/views/meals/shopping_list.html.erb
<div class="page_detail">

  <h1>Shopping List</h1>

  <h3>Your shopping list:</h3>
  <ul class="fa-ul">
    <% @ingredients.each do |i| %>
      <% if i.shopping_list == true %>
        <li><%= link_to '<i class="fa fa-minus-square-o plus_minus_icon"></i>'.html_safe, update_list_path(i.id), method: :patch %>     <%= i.ingredient_name %> </li>
      <% end %>
    <% end %>
  </ul>

  <h3>Ingredients you already have:</h3>
  <ul class="fa-ul">
    <% @ingredients.each do |i| %>
      <% if i.shopping_list == false %>
        <li><%= link_to '<i class="fa fa-plus-square-o plus_minus_icon"></i>'.html_safe, update_list_path(i.id), method: :patch %>     <%= i.ingredient_name %></li>
      <% end %>
    <% end %>
  </ul>

</div>